New info risks table
team408/BIOSQuery-Backend pull request #32
Opened 2024-08-18 13:03 UTC by noyaossi

i added the modal to risks page, to the current main. please let me know if there are some problems. thank you :)

2024-08-18 18:19 UTC, tal-az approved these changes
Minor fixes!
havent ran the code but it doesnt seem to break anything 👍

2024-08-18 18:19 UTC, tal-az commented on controllers/endpoints.js
> +        console.log("Scripts fetched:", scripts);  // Debugging line
remove debug logging from production

2024-08-18 18:19 UTC, tal-az commented on services/fleet.js
> +        console.log(`Scripts for host ${hostId}:`, response.scripts);  // Debugging line
again

2024-08-19 18:44 UTC, maziland requested changes

2024-08-19 18:44 UTC, maziland commented on views/risks.ejs
> +                console.error('Error fetching scripts:', error);
The whole `script` tag should be in a separate `js` files.
I looks great, but it's easier to change and manage when client side javascript is in a separate file.
you should create `public/js/risks.js` and move the content there, then include it in the ejs file like so: `<script src=/js/risks.js></script>

2024-08-20 06:45 UTC, noyaossi commented
i created a new file in public/js/risks.js, and moved the script from views/risks.ejs.

2024-08-23 13:06 UTC, tal-az approved these changes
Note that in statistics.ejs best practice is formatting and crating elements will be done in client side as you've done in public/js/statistics.js. No biggie but for next time. looks good!

2024-08-24 09:06 UTC, maziland approved these changes

2024-08-24 09:08 UTC, merged