Cleanups and bugs
team408/BIOSQuery-Backend pull request #37
Opened 2024-08-23 15:34 UTC by tal-az

Endpoints logic now runs in client side so it's much faster! also notifications cleanup

2024-08-24 09:05 UTC, maziland requested changes

2024-08-24 09:05 UTC, maziland commented on controllers/endpoints.js
> +        res.render("endpoints.ejs", {singleEndpoint: false});
If a single endpoint now has its own EJS, we can remove the `singleEndpoint` param.
Also in line 29 when rendering `single_endpoint.ejs`

2024-08-24 09:05 UTC, maziland commented on public/js/endpoints.js
A few questions:
2. Why did you deleted the Checkboxes javascript?
3. Why did you removed the addNodeModal call and the `addNode` controller?

2024-08-24 09:05 UTC, maziland commented on public/js/notifications.js
> +    const url = `/api/notifications/${readBoolStr}/${id}`;
i think a better uri logic is to have the id before the readBoolStr e.g `/api/notif/144/true`

2024-08-24 09:05 UTC, maziland commented on services/fleet.js
> +async function getScriptBySingleEndpoint(endpoint) {
`getScriptsBySingleEndpoint(endpoint)`
is less confusing - a list of scripts is returned here

2024-08-24 09:35 UTC, tal-az commented on public/js/endpoints.js
By error, worked on a ont up to date main.
will resolve in merge.

2024-08-24 09:47 UTC, tal-az commented on services/fleet.js
> +async function getScriptBySingleEndpoint(endpoint) {
Done altough it's been getScript resulting in an array way before me.

2024-08-24 09:49 UTC, maziland commented on services/fleet.js
> +async function getScriptBySingleEndpoint(endpoint) {
Not blaming you 😅
You can also fix the rest if you'd like

2024-08-24 09:49 UTC, tal-az commented on services/fleet.js
> +async function getScriptBySingleEndpoint(endpoint) {
i did <3

2024-08-24 13:39 UTC, tal-az commented on public/js/endpoints.js
Added both from Gaia's branch manually.
cant test if works, fleet down (syndrome) :(

2024-08-25 06:30 UTC, maziland approved these changes

2024-08-25 22:59 UTC, closed without merging