addNode and start of chipsec control
team408/BIOSQuery-Backend pull request #5
Opened 2024-07-09 21:59 UTC by tal-az

You may now add a node to be managed by fleet via api! ***

Created a new controler - agents, and also new services: system and chipsec (chipsec would be useful for chipsec control).
also updated router accordingly, the api would go by /api/agents/addNode/:os/:host_id

**other requirement**
**in order for add new host to function, the public key of fleet service user should be installed on remote Linux system, and said user's sudoers config should include:
sudo echo <username>	ALL=(ALL:ALL) NOPASSWD: /usr/bin/dpkg >> /etc/sudoers.
username and private key path may be altered in .env as such:
SSH_SECRET_PATH='./secrets/kali.key'
SSH_USERNAME='kali'

2024-07-10 16:45 UTC, maziland requested changes

2024-07-10 16:45 UTC, maziland commented on secrets/kali.key
This is a public repository so you shouldn't upload private keys. I think a better solution for deploying an agent is providing an ip address, username and password. And not by having a private key to all nodes

2024-07-10 16:45 UTC, maziland commented on secrets/kali.key
If you insist on using a private key, read it from env variables or from a specific file system path. Add error handling if the file isn't found

2024-07-10 16:45 UTC, maziland commented on services/chipsec.js
Is it blank because someone else is supposed to write this service?

2024-07-10 16:45 UTC, maziland commented on controllers/agents.js
> +        host_id = req.params.host_id
Check if host_id is in params

2024-07-10 16:45 UTC, maziland commented on controllers/agents.js
> +        osType = req.params.osType;
Check if osType is in params

2024-07-10 16:45 UTC, maziland commented on services/fleet.js
> +async function getAgentEnrollCmd(osType = deb){
deb is not defined, change to "deb"

2024-07-10 16:45 UTC, maziland commented on services/fleet.js
> +    enrollSecret = await fleetApiGetRequest(getSecretUri);
Check the return value of enrollSecret, act differently if null

2024-07-10 16:45 UTC, maziland commented on services/fleet.js
> +    cmd = "fleetctl package --type=" +osType+" --enable-scripts --fleet-url="+fleetUrl+" --enroll-secret="+enrollSecret.spec.secrets[0].secret +";";
what about the "--insecure" flag?
The certificates on the server are self-signed, I'm not sure if it works without it

2024-07-10 16:45 UTC, maziland commented on services/system.js
> +    exec('type .\\scripts\\install_fleet.sh | ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id , (error, stdout, stderr) => {
Don't limit to a windows/linux OS. Use `path.join()` in order to create file paths.
Also remove `type` which is windows only, use `fs.readFileSync` or something

2024-07-10 16:45 UTC, maziland commented on services/system.js
Consider using node-ssh which is a library for ssh connections and script executions.
Using exec with user input is literally a backdoor :)

2024-07-10 16:45 UTC, maziland commented on services/system.js
> +    console.log("[*] Executing: " + 'type .\\scripts\\install_fleet.sh | ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id)
Change this console.log to only print the ip,username for enrollment. Printing the script will be ugly

2024-07-10 16:45 UTC, maziland commented on services/system.js
> +    exec('ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id  + ' \"./' + enrollCmd + ' sudo dpkg -i fleet-osquery*.deb\"', (error, stdout, stderr) => {
backdoor 🥇

2024-07-10 16:45 UTC, maziland commented on services/system.js
> +module.exports = {remoteEnrollLinHost}
Change to `remoteEnrollLinuxHost`

2024-07-10 16:45 UTC, maziland commented on controllers/chipsec.js
> +const modules = ['Banana']
?

2024-07-10 16:45 UTC, maziland commented on routes/router.js
> +router.post("/api/agents/addNode/:osType/:host_id", agentsController.addNode);
Be consistent on camel or snake case

2024-07-10 20:18 UTC, tal-az commented on services/chipsec.js
blank for later implementation of issue "Chipsec Control" by me

2024-07-10 20:26 UTC, tal-az commented on secrets/kali.key
My first approach was requesting as a requirement for OSQuery's deployment that the correlating public key and /etc/ sudoers modification would be made via Ansible. 
Noted, will change for username and password as for my first approach would be redundant because if Ansible is deployed Fleet agent may be deployed also from the Ansible itself without the extra steps.
Thanks.

2024-07-10 20:31 UTC, tal-az commented on routes/router.js
> +router.post("/api/agents/addNode/:osType/:host_id", agentsController.addNode);
Learned a new term.

2024-07-10 20:45 UTC, tal-az commented on services/fleet.js
> +    cmd = "fleetctl package --type=" +osType+" --enable-scripts --fleet-url="+fleetUrl+" --enroll-secret="+enrollSecret.spec.secrets[0].secret +";";
it worked.. adding --insecure just in case

2024-07-10 20:46 UTC, tal-az commented on services/system.js
> +    console.log("[*] Executing: " + 'type .\\scripts\\install_fleet.sh | ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id)
for debug purposes only, deleting.

2024-07-10 20:46 UTC, tal-az commented on services/system.js
noted, will change after POC

2024-07-10 20:47 UTC, tal-az commented on services/system.js
> +    exec('ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id  + ' \"./' + enrollCmd + ' sudo dpkg -i fleet-osquery*.deb\"', (error, stdout, stderr) => {
feature. jk as i said will fix after POC

2024-07-10 20:47 UTC, tal-az commented on services/system.js
> +    exec('type .\\scripts\\install_fleet.sh | ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id , (error, stdout, stderr) => {
noted, will change after POC

2024-07-10 22:59 UTC, tal-az commented on secrets/kali.key
after more research couldnt find one site that supports cleartext password in scripts. all sites support private key.
for now, leaving it as is

2024-07-11 06:56 UTC, maziland approved these changes

2024-07-11 13:52 UTC, merged

2024-07-23 12:36 UTC, tal-az commented on services/system.js
> +    exec('type .\\scripts\\install_fleet.sh | ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id , (error, stdout, stderr) => {
Done

2024-07-23 12:36 UTC, tal-az commented on services/system.js
Done

2024-07-23 12:40 UTC, tal-az commented on services/system.js
> +    exec('ssh -o StrictHostKeyChecking=no -i ' + secret_path + ' ' + username + '@' + host_id  + ' \"./' + enrollCmd + ' sudo dpkg -i fleet-osquery*.deb\"', (error, stdout, stderr) => {
Fixed

2024-07-23 12:41 UTC, tal-az commented on secrets/kali.key
Have added support for both username and password and privatekey.